site_name: ZUtils

plugins:
  - mkdocs-typer2:
      pretty: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - CLI: user-guide/cli.md
    - Download NSRR: user-guide/download-nsrr.md
  - Reference:
    - CLI: reference/cli.md
  - Contributing: contributing.md
  - Release Notes: release-notes.md
