"""Wire-protocol and ZMax TCP client defaults."""

from __future__ import annotations

LIVEMODE_SENDBYTES_COMMAND = "LIVEMODE_SENDBYTES"
DONGLE_MESSAGE_PREFIX = "_DONGLE"

SENDBYTES_MAX_RETRIES = 1
PACKET_TYPE_POSITION = 0
VALID_PACKET_TYPES = range(1, 12)
MIN_DATA_LENGTH = 119
EXPECTED_DATA_LENGTH = MIN_DATA_LENGTH

STIMULATION_RETRY_DELAY = 111
STIMULATION_FLASH_LED_COMMAND = 4
STIMULATION_PWM_MAX = 254
STIMULATION_MAX_REPETITIONS = 127
STIMULATION_MIN_REPETITIONS = 1
STIMULATION_MIN_DURATION = 1
STIMULATION_MAX_DURATION = 255
# Each on/off tick in the stimulation wire packet represents this duration.
STIMULATION_TIME_UNIT_S = 0.1
STIMULATION_MIN_DURATION_S = STIMULATION_MIN_DURATION * STIMULATION_TIME_UNIT_S
STIMULATION_MAX_DURATION_S = STIMULATION_MAX_DURATION * STIMULATION_TIME_UNIT_S

LED_MIN_INTENSITY = 1
LED_MAX_INTENSITY = 100

SAMPLE_RATE = 256.0

DEFAULT_IP = "127.0.0.1"
DEFAULT_PORT = 8000
