"""Wire-protocol and ZMax TCP client defaults."""

from __future__ import annotations

LIVEMODE_SENDBYTES_COMMAND = "LIVEMODE_SENDBYTES"
DONGLE_MESSAGE_PREFIX = "_DONGLE"

SENDBYTES_MAX_RETRIES = 1
PACKET_TYPE_POSITION = 0
VALID_PACKET_TYPES = range(1, 12)
MIN_DATA_LENGTH = 119
EXPECTED_DATA_LENGTH = MIN_DATA_LENGTH

STIMULATION_RETRY_DELAY = 111
STIMULATION_FLASH_LED_COMMAND = 4
STIMULATION_PWM_MAX = 254
STIMULATION_MAX_REPETITIONS = 127
STIMULATION_MIN_REPETITIONS = 1
STIMULATION_MIN_DURATION = 1
STIMULATION_MAX_DURATION = 255

LED_MIN_INTENSITY = 1
LED_MAX_INTENSITY = 100

SAMPLE_RATE = 256.0

DEFAULT_IP = "127.0.0.1"
DEFAULT_PORT = 8000
DEFAULT_SOCKET_TIMEOUT = 1.0

DEFAULTS: dict[str, str | int | float | None] = {
    "ip": DEFAULT_IP,
    "port": DEFAULT_PORT,
    "socket_timeout": DEFAULT_SOCKET_TIMEOUT,
}
